name: John Sexton
favicon: null
layout_spectrum: 0.9573821353260428
typography_spectrum: 0.5188820660114288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5818381474819034
  lightness: 0.589682033052668
  saturation: 0.016606329707428813
  rhythmicContrast: 0.488406655844301
purpose: []
